### ISSUE TITLE
Test Deleting Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#10]
As a **authenticated user** I can **delete tasks** 

**Acceptance Criteria**
- [x] Tasks can be deleted by the owner
- [x] Task can be delete by the assigned teammate

**Tasks**
- [x] Try deleting a task as the owner
- [x] Try deleting a task as a teammate
