### ISSUE TITLE
Test Listing Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#11]
As a **authenticated user** I can **retrieve a list of teams**

**Acceptance Criteria**
- [x] All teams are listed
- [x] Teams can be filtered by username
- [x] Teams can be filtered by title(team name)

**Tasks**
- [x] Request a list of teams and see if the results show all teams
- [x] Filter the list by username
- [x] Filter the list by title
