### ISSUE TITLE
Test Creating Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#12]
As a **authenticated user** I can **create teams** 

**Acceptance Criteria**
- [x] User can create a team
- [x] User creating the team is made the owner of the team
- [x] The created team reflects the submitted data
- [x] The same team cannot be created twice (team.owner + team.name) must be unique

**Tasks**
- [x] Create a team and see if the team reflects the submitted data
- [x] Create the same team twice and see if it works as expected
