### ISSUE TITLE
Test Joining Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#13]
As a **authenticated user** I can **join other teams**

**Acceptance Criteria**
- [x] Membership entry is created correctly - your user becomes member of the targeted team
- [x] Membership allows team owners to assign a task to you as a teammate

**Tasks**
- [x] Join other teams
- [x] Make sure that the membership registers with the owners of the teams you have joined
