### ISSUE TITLE
Test Leaving Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#15]
As a **authenticated user** I can **leave teams**

**Acceptance Criteria**
- [x] Upon leaving a team, the team owner cannot assign tasks to the user
- [x] The membership entry is deleted

**Tasks**
- [x] Leave a team and make sure that the team owner cannot assign tasks to the user
