### ISSUE TITLE
Team List

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#16]
As a **authenticated user** I can **see a list of all teams** 

**Acceptance Criteria**
- [x] Only authenticated users have access to the list
- [x] The list of teams can be searched by username
- [x] The list of teams can be searched by name of team

**Tasks**
- [x] List view for Team model
- [x] Search filter
- [x] Permissions
- [x] Serializer
- [x] URL
