### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#17]
As a **authenticated user** I can **get a list of tasks**

**Acceptance Criteria**
- [x] Only show tasks that were created by the given user or were assigned to the given user 
- [x] Tasks can be sorted by due date
- [x] Tasks can be searched by title
- [x] Tasks can be searched by due date

**Tasks**
- [x] List View for the Task model
- [x] Search filter
- [x] Permissions
- [x] Serializer
- [x] URL
