### ISSUE TITLE
Create Models using ERD

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#18]
As a **developer** I can **store data in a relational database** 

**Tasks**
- [x] Create Model Task
- [x] Create Model Team
- [x] Create Model Membership
- [x] Create Relations among the entities as planned in ERD
