### ISSUE TITLE
Editing Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#23]
**Acceptance criteria**
- [x] Teams are updated correctly 
- [x] Only owner of the team has access

**Tasks**
- [x] View for editing Teams
- [x] Permissions
- [x] URL
