### ISSUE TITLE
Team chat room

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#26]
**Assessment criteria**
- [ ] Leave a message for the team
- [ ] Edit an existing message
- [ ] Delete an existing message
- [ ] View existing messages
- [ ] Messages can only be edited or deleted by their owners
- [ ] Users must be member of the team to view the messages

**Tasks**
- [ ] Generic list view for team chat with create, update and delete functionality
- [ ] View and URL that returns the total of messages in a respective team chat room (for signalling if there are new messages)
- [ ] Permission class (Team owner or Team member)
- [ ] Filter for username
- [ ] Filter for number of messages
