### ISSUE TITLE
Instant notification of changes in the list of teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#29]
**Acceptance criteria**
- [ ] Get a number of teams from the API for the front end

**Tasks**
- [ ] Create View that returns a total number of teams
- [ ] Register the view at a URL route
