### ISSUE TITLE
Creating Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#3]
**Acceptance Criteria**
- [x] Access over POST-method
- [x] Teams created in the Database
- [x] Only authorized users can create Teams
- [x] User who creates the team becomes its owner

**Tasks**
- [x] Model named **Membership**
- [x] Access permissions
- [x] Views with CRUD
- [x] Serializer
- [x] URL
