### ISSUE TITLE
Joining and Leaving Teams

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#4]
**Acceptance criteria**
- [x] Membership can be created over POST-method
- [x] Membership can be deleted over DELETE-method

**Tasks**
- [x] Model named **Membership**
- [x] Access permissions
- [x] Views with Create, Delete, List (Update not necessary)
- [x] Serializer
- [x] URL
