### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#5]
EIC <epic>

As a **developer** I can **use the ERD** so that **I can create a Database in a relational database system**

**Acceptance Criteria**
- [x] Tables are related in a functional manner
- [x] Relationships are normalized
**Tasks**
- [x] Task Relation
- [x] Team Relation
- [x] Team Membership Relation
