### ISSUE TITLE
Test Authentication

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#6]
As a **User** I can **sing in or sign out** so that **I have access to the API**

**Acceptance Criteria**
- [x] settings.py have necessary entries
- [x] JWT is enabled

**Tasks**
- [x] Test logging in as an existing User
- [x] Test registering a User
