### ISSUE TITLE
Test Task Listing

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#7]
As a **User** I can **retrieve a list their own tasks** so that **the front end can display them**

**Acceptance Criteria**
- [x] Tasks list only contains tasks that either belong to the user or have been assigned to the user
- [x] Task list can be ordered by due_date, title
- [x] Task can be searched by title, due_date
- [x] Task list can be filtered by due_date
- [x] Tasks are serialized in JSON format

**Tasks**
- [x] Test Task List without filters
- [x] Test Task with ordering filter
- [x] Test Task with search filter
- [x] Test Task with filter for due_date
- [x] See if the serialized list has all the expected fields
