### ISSUE TITLE
Test Creating Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#8]
As a **authenticated user** I can **create tasks**

**Acceptance Criteria**
- [x] The current user becomes the owner of the task
- [x] Task fields are validated
- [x] The created task reflects the submitted Task

**Tasks**
- [x] Create a new Task
- [x] Try to submit a task with invalid values
- [x] Try to submit a form with empty fields, that are required
- [x] Check the if the returned object in the response reflects the submitted task
