### ISSUE TITLE
Test Updating Tasks

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_api#9]
As an **authenticated user** I can **update tasks**

**Acceptance Criteria**
- [x] The updated task reflects the submitted data 
- [x] Access granted only to the owner or a teammate, to whom the task was assigned

**Tasks**
- [x] Open an existing task, that you own and edit it
- [x] Open an existing task, to which you were assigned, and edit it
- [x] Append or remove a file
